  version: 2
  updates:
    - directory: "/"
      package-ecosystem: gradle
      open-pull-requests-limit: 2
      schedule:
        interval: weekly
        day: wednesday
      reviewers:
        - wadoon
