version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    reviewers:
      - wadoon
    schedule:
      interval: "weekly"
    groups:
      gradle:
        patterns:
          - "*"      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
